.PHONY: all pip_install_user

all:
	@ echo "tensorflow quantize module"

pip_install_user:
	@ pip install --upgrade --no-deps --force-reinstall --user .

pip_install:
	@ pip install --upgrade --no-deps --force-reinstall .
